Update auto.yml

diff --git a/.github/workflows/auto.yml b/.github/workflows/auto.yml
--- a/.github/workflows/auto.yml
+++ b/.github/workflows/auto.yml
@@ -43,6 +43,7 @@ jobs:
         uses: actions/checkout@v2
         with:
           repository: ${{ inputs.repoPath }}
+          ref: main
 
       - name: Set up GitHub Token for Authentication
         run: |
@@ -50,6 +51,16 @@ jobs:
           git config --global user.email "actions@github.com"
           git config --global credential.helper store
           echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
+
+
+      - name: Debug Information
+        run: |
+          echo "Action: ${{ inputs.action }}"
+          echo "Submodule URL: ${{ inputs.submoduleUrl }}"
+          echo "Submodule Path: ${{ inputs.submodulePath }}"
+          echo "Submodule Commit: ${{ inputs.submoduleCommit }}"
+          git status
+          cat .gitmodules || echo ".gitmodules file not found"
 
       # Add Submodule (if action is '1')
       - name: Add Submodule
